### ISSUE TITLE
I can't run the demo, it provides a error, Object(...) is not a function

### ISSUE THREAD

**Issue by longmartin** [udevbe/tinyh264#6]

**Comment by Zubnix** [comment]
I've updated the demo and tested it on my end using a fresh clone. Can you confirm it works on your end as well?

**Comment by longmartin** [comment]
when I run this demo, it still provides an error .
H264NALDecoder.worker.js:5 Uncaught TypeError: Object(...) is not a function at eval (H264NALDecoder.worker.js:5)

the version of tinyh264 is 0.0.3, but the package version at npm  is 0.0.1 

 does it work on your end?

**Comment by Zubnix** [comment]
Good catch. Version 0.0.3 (with the fix) should be available now on npm.

**Comment by longmartin** [comment]
import the package, function init is undefined, I think init may be call by promise. 
when I console.log init, it shows undefined, I think the code of "exports {init}" doesn't work. 
can you run the demo on your machine?

**Comment by longmartin** [comment]
when I use the lastest demo , it runs well .  but I can't find the differences between 0.0.1 and 0.0.3。 could you tell me  your changes of code

**Comment by Zubnix** [comment]
There's a file in 0.0.1 with name `foo.worker.js` This is picked up by webpack and treated as stand-alone webworker (which is not the intention). Inside the demo project is the actual `bar.worker.js` that imports `foo.worker.js` and the result is a worker that spawns a worker... the result is a mess that gives this error.

**Comment by longmartin** [comment]
Thank you @Zubnix for your lastest answer. 
But I use another file of h264, that decoder fails, it provide "TinyH264Decoder.ERROR = 3 or
TinyH264Decoder.PARAM_SET_ERROR = 4". if I should discard some frame?

**Comment by Zubnix** [comment]
I'm not sure what the problem is. It is perhaps important to know that TinyH264 only handles `restricted-baseline` and `baseline` decoding. Anything more will probably not work. You also have to feed it exact h264 Access Units (AU), which is basically a complete frame and consists of 1 or more H264 Network Abstraction Layer Units (NAL(U)s). If you give it the whole file at once, it won't really know how to read the next AU, you'll need an H264 (stream) parser for that.
